### PR TITLE
Skip sqlite3 tables with incorrect table_info

### LINKED ISSUE #180: Skip sqlite3 tables with incorrect table_info
I have a third party database that I cannot change it. Is there a way to silently fail and still generate the _correct_ entities?

```
reform-db: 2018/11/10 04:33:51.656895 cmd_init_sqlite3.go:85: no such module: spellfix1
panic: no such module: spellfix1

goroutine 1 [running]:
gopkg.in/reform.v1/internal.(*Logger).Fatalf(0xc0000938f0, 0x45377d0, 0x2, 0xc000348a60, 0x1, 0x1)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/internal/logger.go:51 +0x107
main.initModelsSQLite3(0xc00009c8a0, 0xc0000dbbd0, 0x400b9bd, 0x44dd240)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/cmd_init_sqlite3.go:85 +0x469
main.cmdInit(0xc00009c8a0, 0xc00001e004, 0x1f)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/cmd_init.go:184 +0xb2f
main.main()
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/main.go:128 +0x3a4
```

Something like the following:

https://stackoverflow.com/questions/38425835/reflecting-sqlite-database-with-spellfix1-tables

Edit:
Even better, something like `--skip-tables` I think would be less invasive?

### PR DESCRIPTION
**Pull request by AlekSi**
Closes #180.

### CODE REVIEW

File: reform-db/cmd_init_sqlite3.go [hunk 1]
```diff
@@ -82,7 +82,9 @@ func initModelsSQLite3(db *reform.DB) (structs []StructData) {
 
 		rows, err := db.Query("PRAGMA table_info(" + tableName + ")") // no placeholders for PRAGMA
 		if err != nil {
-			logger.Fatalf("%s", err)
+			// https://github.com/go-reform/reform/issues/180
+			logger.Printf("Skipping %s: %s.", tableName, err)
```
Comment (rumyantseva) [inline reform-db/cmd_init_sqlite3.go:86]: Ok, I can't review these changes because the whole code of this function confuses me a lot... cyclomatic complexity makes it unreadable to me, sorry :/ 

For example, on the line 108 you check an error... Where is this error from? Is it from line 91? Or is it from the line 83?.. Quite unclear to me from the first sight...

The change itself is probably ok, it doesn't seem to make the code worse, but the function is not simple. If you are interested, I'd offer a pair programming session to maybe refactor it (as a part of some other issue / PR).

Comment (rumyantseva) [reply reform-db/cmd_init_sqlite3.go:86]: P.S. Maybe it might be helpful to add a test to cover this case - when one of the tables gets error here...
